name: HardenEKS Scan

on:
  workflow_dispatch: {}  # 수동 실행
  # schedule:
  #   - cron: '0 18 * * *'  # (옵션) 매일 03:00 KST (18:00 UTC) 실행

permissions:
  id-token: write   # OIDC로 IAM 역할 가정
  contents: read

env:
  REPORT_DIR: reports/${{ secrets.EKS_CLUSTER_NAME }}

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup AWS CLI
        uses: aws-actions/setup-aws-cli@v2

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_HARDENEKS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region "${{ secrets.AWS_REGION }}" \
            --name   "${{ secrets.EKS_CLUSTER_NAME }}"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install hardeneks (pin)
        run: |
          python -m pip install --upgrade pip
          pip install 'hardeneks==0.11.2'
          python -c "import hardeneks,sys;print('hardeneks', hardeneks.__version__)"

      - name: Run HardenEKS
        shell: bash
        run: |
          mkdir -p "$REPORT_DIR"
          CFG=""
          if [ -f config/config.yaml ]; then
            CFG="--config config/config.yaml"
          fi

          hardeneks \
            --region "${{ secrets.AWS_REGION }}" \
            --cluster "${{ secrets.EKS_CLUSTER_NAME }}" \
            $CFG \
            --export-html "$REPORT_DIR/report.html" \
            --export-json "$REPORT_DIR/report.json" \
            --export-csv  "$REPORT_DIR/report.csv"

      - name: Upload report artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hardeneks-report-${{ secrets.EKS_CLUSTER_NAME }}
          path: ${{ env.REPORT_DIR }}/
          retention-days: 14
          if-no-files-found: error
