name: HardenEKS Scan

on:
  workflow_dispatch: {}  # 수동 실행
  # schedule:
  #   - cron: '0 18 * * *'  # (옵션) 매일 03:00 KST (18:00 UTC) 실행

permissions:
  id-token: write   # OIDC로 IAM 역할 가정
  contents: read

env:
  REPORT_DIR: reports/${{ secrets.EKS_CLUSTER_NAME }}

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: ${{ secrets.AWS_HARDENEKS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region "${{ secrets.AWS_REGION }}" \
            --name   "${{ secrets.EKS_CLUSTER_NAME }}"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create venv & install HardenEKS
        run: |
          python3 -m venv /tmp/.venv
          source /tmp/.venv/bin/activate
          pip install hardeneks
          echo "/tmp/.venv/bin" >> "$GITHUB_PATH"   # 이후 스텝에서 hardeneks 바로 호출 가능

      - name: Run HardenEKS
        run: |
          hardeneks \
            --region "${{ secrets.AWS_REGION }}" \
            --cluster "${{ secrets.EKS_CLUSTER_NAME }}" \
            --config config/config.yaml \
            --export-html "$REPORT_DIR/report.html" \
            --export-json "$REPORT_DIR/report.json" \
            --export-csv  "$REPORT_DIR/report.csv"

      - name: Upload report artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hardeneks-report-${{ secrets.EKS_CLUSTER_NAME }}
          path: ${{ env.REPORT_DIR }}/
          retention-days: 14
          if-no-files-found: error
